/*
 * Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plugint.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.plugint.client.model.IntegrationApiModelsCommandsPersonalDetails;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Details of an Online journey. Required if the Origin is set to \&quot;Online\&quot;
 */
@Schema(description = "Details of an Online journey. Required if the Origin is set to \"Online\"")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-24T06:53:25.443Z[GMT]")
public class IntegrationApiModelsCommandsOnlineJourneyDetails {
  @SerializedName("callbackUrl")
  private String callbackUrl = null;

  @SerializedName("cancelUrl")
  private String cancelUrl = null;

  @SerializedName("failUrl")
  private String failUrl = null;

  @SerializedName("planCreationType")
  private String planCreationType = null;

  @SerializedName("chargeBackCount")
  private Integer chargeBackCount = null;

  @SerializedName("customerQuality")
  private Integer customerQuality = null;

  @SerializedName("customerDetails")
  private IntegrationApiModelsCommandsPersonalDetails customerDetails = null;

  @SerializedName("deliveryDate")
  private String deliveryDate = null;
  
  @SerializedName("deliveryMethod")
  private String deliveryMethod = null;

  public IntegrationApiModelsCommandsOnlineJourneyDetails callbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * URL to redirect to upon successful plan creation or lodgement (may also serve as the only one, as it has parameter ‘status’: SUCCESS, LODGED, CANCELLED, FAILED)
   * @return callbackUrl
  **/
  @Schema(required = true, description = "URL to redirect to upon successful plan creation or lodgement (may also serve as the only one, as it has parameter ‘status’: SUCCESS, LODGED, CANCELLED, FAILED)")
  public String getCallbackUrl() {
    return callbackUrl;
  }

  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  public IntegrationApiModelsCommandsOnlineJourneyDetails cancelUrl(String cancelUrl) {
    this.cancelUrl = cancelUrl;
    return this;
  }

   /**
   * URL to redirect to when user cancels the plan creation or lodgement
   * @return cancelUrl
  **/
  @Schema(required = true, description = "URL to redirect to when user cancels the plan creation or lodgement")
  public String getCancelUrl() {
    return cancelUrl;
  }

  public void setCancelUrl(String cancelUrl) {
    this.cancelUrl = cancelUrl;
  }

  public IntegrationApiModelsCommandsOnlineJourneyDetails failUrl(String failUrl) {
    this.failUrl = failUrl;
    return this;
  }

   /**
   * URL to redirect to when a system error occurs
   * @return failUrl
  **/
  @Schema(required = true, description = "URL to redirect to when a system error occurs")
  public String getFailUrl() {
    return failUrl;
  }

  public void setFailUrl(String failUrl) {
    this.failUrl = failUrl;
  }

  public IntegrationApiModelsCommandsOnlineJourneyDetails planCreationType(String planCreationType) {
    this.planCreationType = planCreationType;
    return this;
  }

   /**
   * Based on this flag, plan will be created as pending capture
   * @return planCreationType
  **/
  @Schema(required = true, description = "Based on this flag, plan will be created as pending capture")
  public String getPlanCreationType() {
    return planCreationType;
  }

  public void setPlanCreationType(String planCreationType) {
    this.planCreationType = planCreationType;
  }

  public IntegrationApiModelsCommandsOnlineJourneyDetails chargeBackCount(Integer chargeBackCount) {
    this.chargeBackCount = chargeBackCount;
    return this;
  }

   /**
   * How many chargebacks are known to have been received from this customer?  -1 &#x3D; Unknown (default)
   * @return chargeBackCount
  **/
  @Schema(description = "How many chargebacks are known to have been received from this customer?  -1 = Unknown (default)")
  public Integer getChargeBackCount() {
    return chargeBackCount;
  }

  public void setChargeBackCount(Integer chargeBackCount) {
    this.chargeBackCount = chargeBackCount;
  }

  public IntegrationApiModelsCommandsOnlineJourneyDetails customerQuality(Integer customerQuality) {
    this.customerQuality = customerQuality;
    return this;
  }

   /**
   * How is this customer categorised?  -1&#x3D; Unknown (default)  0 &#x3D; Brand new with no history  1 &#x3D; Returning ‘Good’ customer  2 &#x3D; Returning ‘Average’ customer  3 &#x3D; Returning ‘Bad’ customer
   * @return customerQuality
  **/
  @Schema(description = "How is this customer categorised?  -1= Unknown (default)  0 = Brand new with no history  1 = Returning ‘Good’ customer  2 = Returning ‘Average’ customer  3 = Returning ‘Bad’ customer")
  public Integer getCustomerQuality() {
    return customerQuality;
  }

  public void setCustomerQuality(Integer customerQuality) {
    this.customerQuality = customerQuality;
  }

  public IntegrationApiModelsCommandsOnlineJourneyDetails customerDetails(IntegrationApiModelsCommandsPersonalDetails customerDetails) {
    this.customerDetails = customerDetails;
    return this;
  }

   /**
   * Get customerDetails
   * @return customerDetails
  **/
  @Schema(required = true, description = "")
  public IntegrationApiModelsCommandsPersonalDetails getCustomerDetails() {
    return customerDetails;
  }

  public void setCustomerDetails(IntegrationApiModelsCommandsPersonalDetails customerDetails) {
    this.customerDetails = customerDetails;
  }

  public IntegrationApiModelsCommandsOnlineJourneyDetails deliveryDate(String deliveryDate) {
    this.deliveryDate = deliveryDate;
    return this;
  }
  
  public IntegrationApiModelsCommandsOnlineJourneyDetails deliveryMethod(String deliveryMethod) {
	    this.deliveryMethod = deliveryMethod;
	    return this;
	  }

   /**
   * The date for which the delivery is scheduled
   * @return deliveryDate
  **/
  @Schema(description = "The date for which the delivery is scheduled")
  public String getDeliveryDate() {
    return deliveryDate;
  }

  public void setDeliveryDate(String deliveryDate) {
    this.deliveryDate = deliveryDate;
  }
  
  /**
   * If Click and Collect is selected on Checkout, please set deliveryMethod to "Pickup" and pass the store address in the "deliveryAddress" fields. If the digital services are provided to the customers where goods are not delivered to any physical address, please set "Email" that applies to digital goods. Merchant is not required to pass the "deliveryAddress"
   * @return DeliveryMethod
  **/
  @Schema(description = "The date for which the delivery is scheduled")
  public String getDeliveryMethod() {
    return deliveryMethod;
  }

  public void setDeliveryMethod(String deliveryMethod) {
    this.deliveryMethod = deliveryMethod;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationApiModelsCommandsOnlineJourneyDetails integrationApiModelsCommandsOnlineJourneyDetails = (IntegrationApiModelsCommandsOnlineJourneyDetails) o;
    return Objects.equals(this.callbackUrl, integrationApiModelsCommandsOnlineJourneyDetails.callbackUrl) &&
        Objects.equals(this.cancelUrl, integrationApiModelsCommandsOnlineJourneyDetails.cancelUrl) &&
        Objects.equals(this.failUrl, integrationApiModelsCommandsOnlineJourneyDetails.failUrl) &&
        Objects.equals(this.planCreationType, integrationApiModelsCommandsOnlineJourneyDetails.planCreationType) &&
        Objects.equals(this.chargeBackCount, integrationApiModelsCommandsOnlineJourneyDetails.chargeBackCount) &&
        Objects.equals(this.customerQuality, integrationApiModelsCommandsOnlineJourneyDetails.customerQuality) &&
        Objects.equals(this.customerDetails, integrationApiModelsCommandsOnlineJourneyDetails.customerDetails) &&
        Objects.equals(this.deliveryDate, integrationApiModelsCommandsOnlineJourneyDetails.deliveryDate) &&
        Objects.equals(this.deliveryMethod, integrationApiModelsCommandsOnlineJourneyDetails.deliveryMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callbackUrl, cancelUrl, failUrl, planCreationType, chargeBackCount, customerQuality, customerDetails, deliveryDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationApiModelsCommandsOnlineJourneyDetails {\n");
    
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    cancelUrl: ").append(toIndentedString(cancelUrl)).append("\n");
    sb.append("    failUrl: ").append(toIndentedString(failUrl)).append("\n");
    sb.append("    planCreationType: ").append(toIndentedString(planCreationType)).append("\n");
    sb.append("    chargeBackCount: ").append(toIndentedString(chargeBackCount)).append("\n");
    sb.append("    customerQuality: ").append(toIndentedString(customerQuality)).append("\n");
    sb.append("    customerDetails: ").append(toIndentedString(customerDetails)).append("\n");
    sb.append("    deliveryDate: ").append(toIndentedString(deliveryDate)).append("\n");
    sb.append("    deliveryMethod: ").append(toIndentedString(deliveryMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
