/*
 * Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plugint.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The next action to take in the flow. Depending on the type, it may be accompanied by a matching object with details.
 */
@JsonAdapter(IntegrationApiModelsNextActionType.Adapter.class)
public enum IntegrationApiModelsNextActionType {
  FORMPOST("FormPost"),
  WAITFORCUSTOMER("WaitForCustomer");

  private String value;

  IntegrationApiModelsNextActionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static IntegrationApiModelsNextActionType fromValue(String text) {
    for (IntegrationApiModelsNextActionType b : IntegrationApiModelsNextActionType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<IntegrationApiModelsNextActionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final IntegrationApiModelsNextActionType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public IntegrationApiModelsNextActionType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return IntegrationApiModelsNextActionType.fromValue(String.valueOf(value));
    }
  }
}
