/*
 * Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plugint.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.plugint.client.model.IntegrationApiModelsFormPostAction;
import com.plugint.client.model.IntegrationApiModelsNextActionType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Describes the next action in the flow and the details necessary to take that action
 */
@Schema(description = "Describes the next action in the flow and the details necessary to take that action")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-24T06:53:25.443Z[GMT]")
public class IntegrationApiModelsNextAction {
  @SerializedName("type")
  private IntegrationApiModelsNextActionType type = null;

  @SerializedName("formPost")
  private IntegrationApiModelsFormPostAction formPost = null;

  public IntegrationApiModelsNextAction type(IntegrationApiModelsNextActionType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public IntegrationApiModelsNextActionType getType() {
    return type;
  }

  public void setType(IntegrationApiModelsNextActionType type) {
    this.type = type;
  }

  public IntegrationApiModelsNextAction formPost(IntegrationApiModelsFormPostAction formPost) {
    this.formPost = formPost;
    return this;
  }

   /**
   * Get formPost
   * @return formPost
  **/
  @Schema(description = "")
  public IntegrationApiModelsFormPostAction getFormPost() {
    return formPost;
  }

  public void setFormPost(IntegrationApiModelsFormPostAction formPost) {
    this.formPost = formPost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationApiModelsNextAction integrationApiModelsNextAction = (IntegrationApiModelsNextAction) o;
    return Objects.equals(this.type, integrationApiModelsNextAction.type) &&
        Objects.equals(this.formPost, integrationApiModelsNextAction.formPost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, formPost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationApiModelsNextAction {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    formPost: ").append(toIndentedString(formPost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
