/*
 * Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plugint.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IntegrationApiModelsCommandsAddress
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-24T06:53:25.443Z[GMT]")
public class IntegrationApiModelsCommandsAddress {
  @SerializedName("line1")
  private String line1 = null;

  @SerializedName("line2")
  private String line2 = null;

  @SerializedName("suburb")
  private String suburb = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("postCode")
  private String postCode = null;

  public IntegrationApiModelsCommandsAddress line1(String line1) {
    this.line1 = line1;
    return this;
  }

   /**
   * The first address line
   * @return line1
  **/
  @Schema(required = true, description = "The first address line")
  public String getLine1() {
    return line1;
  }

  public void setLine1(String line1) {
    this.line1 = line1;
  }

  public IntegrationApiModelsCommandsAddress line2(String line2) {
    this.line2 = line2;
    return this;
  }

   /**
   * The second address line
   * @return line2
  **/
  @Schema(description = "The second address line")
  public String getLine2() {
    return line2;
  }

  public void setLine2(String line2) {
    this.line2 = line2;
  }

  public IntegrationApiModelsCommandsAddress suburb(String suburb) {
    this.suburb = suburb;
    return this;
  }

   /**
   * The address suburb, town or county
   * @return suburb
  **/
  @Schema(required = true, description = "The address suburb, town or county")
  public String getSuburb() {
    return suburb;
  }

  public void setSuburb(String suburb) {
    this.suburb = suburb;
  }

  public IntegrationApiModelsCommandsAddress state(String state) {
    this.state = state;
    return this;
  }

   /**
   * The address state
   * @return state
  **/
  @Schema(required = true, description = "The address state")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public IntegrationApiModelsCommandsAddress postCode(String postCode) {
    this.postCode = postCode;
    return this;
  }

   /**
   * The address postcode    Format: AUS: NNNN (zero-padded to the left)  Format: UK: XXXXXXXX (may have space)
   * @return postCode
  **/
  @Schema(required = true, description = "The address postcode    Format: AUS: NNNN (zero-padded to the left)  Format: UK: XXXXXXXX (may have space)")
  public String getPostCode() {
    return postCode;
  }

  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationApiModelsCommandsAddress integrationApiModelsCommandsAddress = (IntegrationApiModelsCommandsAddress) o;
    return Objects.equals(this.line1, integrationApiModelsCommandsAddress.line1) &&
        Objects.equals(this.line2, integrationApiModelsCommandsAddress.line2) &&
        Objects.equals(this.suburb, integrationApiModelsCommandsAddress.suburb) &&
        Objects.equals(this.state, integrationApiModelsCommandsAddress.state) &&
        Objects.equals(this.postCode, integrationApiModelsCommandsAddress.postCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(line1, line2, suburb, state, postCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationApiModelsCommandsAddress {\n");
    
    sb.append("    line1: ").append(toIndentedString(line1)).append("\n");
    sb.append("    line2: ").append(toIndentedString(line2)).append("\n");
    sb.append("    suburb: ").append(toIndentedString(suburb)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    postCode: ").append(toIndentedString(postCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
