/*
 * Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plugint.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IntegrationApiModelsCommandsCartItem
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-24T06:53:25.443Z[GMT]")
public class IntegrationApiModelsCommandsCartItem {
  @SerializedName("itemName")
  private String itemName = null;

  @SerializedName("itemGroup")
  private String itemGroup = null;

  @SerializedName("itemCode")
  private String itemCode = null;

  @SerializedName("itemGroupCode")
  private String itemGroupCode = null;

  @SerializedName("itemRetailUnitPrice")
  private Integer itemRetailUnitPrice = null;

  @SerializedName("itemQty")
  private String itemQty = null;

  @SerializedName("itemRetailCharge")
  private Integer itemRetailCharge = null;

  public IntegrationApiModelsCommandsCartItem itemName(String itemName) {
    this.itemName = itemName;
    return this;
  }

   /**
   * A description of the item used by the retailer
   * @return itemName
  **/
  @Schema(required = true, description = "A description of the item used by the retailer")
  public String getItemName() {
    return itemName;
  }

  public void setItemName(String itemName) {
    this.itemName = itemName;
  }

  public IntegrationApiModelsCommandsCartItem itemGroup(String itemGroup) {
    this.itemGroup = itemGroup;
    return this;
  }

   /**
   * A group level description if available
   * @return itemGroup
  **/
  @Schema(description = "A group level description if available")
  public String getItemGroup() {
    return itemGroup;
  }

  public void setItemGroup(String itemGroup) {
    this.itemGroup = itemGroup;
  }

  public IntegrationApiModelsCommandsCartItem itemCode(String itemCode) {
    this.itemCode = itemCode;
    return this;
  }

   /**
   * An internal stock number for this item
   * @return itemCode
  **/
  @Schema(required = true, description = "An internal stock number for this item")
  public String getItemCode() {
    return itemCode;
  }

  public void setItemCode(String itemCode) {
    this.itemCode = itemCode;
  }

  public IntegrationApiModelsCommandsCartItem itemGroupCode(String itemGroupCode) {
    this.itemGroupCode = itemGroupCode;
    return this;
  }

   /**
   * If a group has an internal code that may be used to refer to it, it can be supplied
   * @return itemGroupCode
  **/
  @Schema(description = "If a group has an internal code that may be used to refer to it, it can be supplied")
  public String getItemGroupCode() {
    return itemGroupCode;
  }

  public void setItemGroupCode(String itemGroupCode) {
    this.itemGroupCode = itemGroupCode;
  }

  public IntegrationApiModelsCommandsCartItem itemRetailUnitPrice(Integer itemRetailUnitPrice) {
    this.itemRetailUnitPrice = itemRetailUnitPrice;
    return this;
  }

   /**
   * The individual retail price charged for the item  An integer number in the lowest denomination in the currency being used (e.g. 1034 indicates $10.34)
   * @return itemRetailUnitPrice
  **/
  @Schema(required = true, description = "The individual retail price charged for the item  An integer number in the lowest denomination in the currency being used (e.g. 1034 indicates $10.34)")
  public Integer getItemRetailUnitPrice() {
    return itemRetailUnitPrice;
  }

  public void setItemRetailUnitPrice(Integer itemRetailUnitPrice) {
    this.itemRetailUnitPrice = itemRetailUnitPrice;
  }

  public IntegrationApiModelsCommandsCartItem itemQty(String itemQty) {
    this.itemQty = itemQty;
    return this;
  }

   /**
   * How many of the items were purchased
   * @return itemQty
  **/
  @Schema(required = true, description = "How many of the items were purchased")
  public String getItemQty() {
    return itemQty;
  }

  public void setItemQty(String itemQty) {
    this.itemQty = itemQty;
  }

  public IntegrationApiModelsCommandsCartItem itemRetailCharge(Integer itemRetailCharge) {
    this.itemRetailCharge = itemRetailCharge;
    return this;
  }

   /**
   * The overall retail charge for the quantity of items  An integer number in the lowest denomination in the currency being used (e.g. 1034 indicates $10.34)
   * @return itemRetailCharge
  **/
  @Schema(required = true, description = "The overall retail charge for the quantity of items  An integer number in the lowest denomination in the currency being used (e.g. 1034 indicates $10.34)")
  public Integer getItemRetailCharge() {
    return itemRetailCharge;
  }

  public void setItemRetailCharge(Integer itemRetailCharge) {
    this.itemRetailCharge = itemRetailCharge;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationApiModelsCommandsCartItem integrationApiModelsCommandsCartItem = (IntegrationApiModelsCommandsCartItem) o;
    return Objects.equals(this.itemName, integrationApiModelsCommandsCartItem.itemName) &&
        Objects.equals(this.itemGroup, integrationApiModelsCommandsCartItem.itemGroup) &&
        Objects.equals(this.itemCode, integrationApiModelsCommandsCartItem.itemCode) &&
        Objects.equals(this.itemGroupCode, integrationApiModelsCommandsCartItem.itemGroupCode) &&
        Objects.equals(this.itemRetailUnitPrice, integrationApiModelsCommandsCartItem.itemRetailUnitPrice) &&
        Objects.equals(this.itemQty, integrationApiModelsCommandsCartItem.itemQty) &&
        Objects.equals(this.itemRetailCharge, integrationApiModelsCommandsCartItem.itemRetailCharge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemName, itemGroup, itemCode, itemGroupCode, itemRetailUnitPrice, itemQty, itemRetailCharge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationApiModelsCommandsCartItem {\n");
    
    sb.append("    itemName: ").append(toIndentedString(itemName)).append("\n");
    sb.append("    itemGroup: ").append(toIndentedString(itemGroup)).append("\n");
    sb.append("    itemCode: ").append(toIndentedString(itemCode)).append("\n");
    sb.append("    itemGroupCode: ").append(toIndentedString(itemGroupCode)).append("\n");
    sb.append("    itemRetailUnitPrice: ").append(toIndentedString(itemRetailUnitPrice)).append("\n");
    sb.append("    itemQty: ").append(toIndentedString(itemQty)).append("\n");
    sb.append("    itemRetailCharge: ").append(toIndentedString(itemRetailCharge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
