/*
 * Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plugint.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Details of a POS Web journey. Required if the Origin is set to \&quot;PosWeb\&quot;
 */
@Schema(description = "Details of a POS Web journey. Required if the Origin is set to \"PosWeb\"")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-24T06:53:25.443Z[GMT]")
public class IntegrationApiModelsCommandsPosWebJourneyDetails {
  @SerializedName("planCreationType")
  private String planCreationType = null;

  @SerializedName("employeeCode")
  private String employeeCode = null;

  @SerializedName("callbackUrl")
  private String callbackUrl = null;

  @SerializedName("cancelUrl")
  private String cancelUrl = null;

  @SerializedName("failUrl")
  private String failUrl = null;

  public IntegrationApiModelsCommandsPosWebJourneyDetails planCreationType(String planCreationType) {
    this.planCreationType = planCreationType;
    return this;
  }

   /**
   * Based on this flag, plan will be created as pending capture
   * @return planCreationType
  **/
  @Schema(required = true, description = "Based on this flag, plan will be created as pending capture")
  public String getPlanCreationType() {
    return planCreationType;
  }

  public void setPlanCreationType(String planCreationType) {
    this.planCreationType = planCreationType;
  }

  public IntegrationApiModelsCommandsPosWebJourneyDetails employeeCode(String employeeCode) {
    this.employeeCode = employeeCode;
    return this;
  }

   /**
   * The name, number or code representing the individual who created the order
   * @return employeeCode
  **/
  @Schema(description = "The name, number or code representing the individual who created the order")
  public String getEmployeeCode() {
    return employeeCode;
  }

  public void setEmployeeCode(String employeeCode) {
    this.employeeCode = employeeCode;
  }

  public IntegrationApiModelsCommandsPosWebJourneyDetails callbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * URL to redirect to upon successful plan creation or lodgement (may also serve as the only one, as it has parameter ‘status’: SUCCESS, LODGED, CANCELLED, FAILED)
   * @return callbackUrl
  **/
  @Schema(required = true, description = "URL to redirect to upon successful plan creation or lodgement (may also serve as the only one, as it has parameter ‘status’: SUCCESS, LODGED, CANCELLED, FAILED)")
  public String getCallbackUrl() {
    return callbackUrl;
  }

  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  public IntegrationApiModelsCommandsPosWebJourneyDetails cancelUrl(String cancelUrl) {
    this.cancelUrl = cancelUrl;
    return this;
  }

   /**
   * URL to redirect to when user cancels the plan creation or lodgement
   * @return cancelUrl
  **/
  @Schema(required = true, description = "URL to redirect to when user cancels the plan creation or lodgement")
  public String getCancelUrl() {
    return cancelUrl;
  }

  public void setCancelUrl(String cancelUrl) {
    this.cancelUrl = cancelUrl;
  }

  public IntegrationApiModelsCommandsPosWebJourneyDetails failUrl(String failUrl) {
    this.failUrl = failUrl;
    return this;
  }

   /**
   * URL to redirect to when a system error occurs
   * @return failUrl
  **/
  @Schema(required = true, description = "URL to redirect to when a system error occurs")
  public String getFailUrl() {
    return failUrl;
  }

  public void setFailUrl(String failUrl) {
    this.failUrl = failUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationApiModelsCommandsPosWebJourneyDetails integrationApiModelsCommandsPosWebJourneyDetails = (IntegrationApiModelsCommandsPosWebJourneyDetails) o;
    return Objects.equals(this.planCreationType, integrationApiModelsCommandsPosWebJourneyDetails.planCreationType) &&
        Objects.equals(this.employeeCode, integrationApiModelsCommandsPosWebJourneyDetails.employeeCode) &&
        Objects.equals(this.callbackUrl, integrationApiModelsCommandsPosWebJourneyDetails.callbackUrl) &&
        Objects.equals(this.cancelUrl, integrationApiModelsCommandsPosWebJourneyDetails.cancelUrl) &&
        Objects.equals(this.failUrl, integrationApiModelsCommandsPosWebJourneyDetails.failUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(planCreationType, employeeCode, callbackUrl, cancelUrl, failUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationApiModelsCommandsPosWebJourneyDetails {\n");
    
    sb.append("    planCreationType: ").append(toIndentedString(planCreationType)).append("\n");
    sb.append("    employeeCode: ").append(toIndentedString(employeeCode)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    cancelUrl: ").append(toIndentedString(cancelUrl)).append("\n");
    sb.append("    failUrl: ").append(toIndentedString(failUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
