/*
 * Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plugint.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of customer journey being started
 */
@JsonAdapter(IntegrationApiModelsCommandsOrderOrigin.Adapter.class)
public enum IntegrationApiModelsCommandsOrderOrigin {
  ONLINE("Online"),
  POSAPP("PosApp"),
  POSWEB("PosWeb");

  private String value;

  IntegrationApiModelsCommandsOrderOrigin(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static IntegrationApiModelsCommandsOrderOrigin fromValue(String text) {
    for (IntegrationApiModelsCommandsOrderOrigin b : IntegrationApiModelsCommandsOrderOrigin.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<IntegrationApiModelsCommandsOrderOrigin> {
    @Override
    public void write(final JsonWriter jsonWriter, final IntegrationApiModelsCommandsOrderOrigin enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public IntegrationApiModelsCommandsOrderOrigin read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return IntegrationApiModelsCommandsOrderOrigin.fromValue(String.valueOf(value));
    }
  }
}
