/*
 * Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plugint.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Details of a POS APP journey. Required if the Origin is set to \&quot;PosApp\&quot;
 */
@Schema(description = "Details of a POS APP journey. Required if the Origin is set to \"PosApp\"")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-24T06:53:25.443Z[GMT]")
public class IntegrationApiModelsCommandsPosAppJourneyDetails {
  @SerializedName("employeeCode")
  private String employeeCode = null;

  @SerializedName("customerId")
  private String customerId = null;

  public IntegrationApiModelsCommandsPosAppJourneyDetails employeeCode(String employeeCode) {
    this.employeeCode = employeeCode;
    return this;
  }

   /**
   * The name, number or code representing the individual who created the order
   * @return employeeCode
  **/
  @Schema(description = "The name, number or code representing the individual who created the order")
  public String getEmployeeCode() {
    return employeeCode;
  }

  public void setEmployeeCode(String employeeCode) {
    this.employeeCode = employeeCode;
  }

  public IntegrationApiModelsCommandsPosAppJourneyDetails customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * The specific numeric Customer ID supplied by the customer from their App if they have it  If it is not supplied, it is expected that the sales process will be Retailer Lead
   * @return customerId
  **/
  @Schema(description = "The specific numeric Customer ID supplied by the customer from their App if they have it  If it is not supplied, it is expected that the sales process will be Retailer Lead")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationApiModelsCommandsPosAppJourneyDetails integrationApiModelsCommandsPosAppJourneyDetails = (IntegrationApiModelsCommandsPosAppJourneyDetails) o;
    return Objects.equals(this.employeeCode, integrationApiModelsCommandsPosAppJourneyDetails.employeeCode) &&
        Objects.equals(this.customerId, integrationApiModelsCommandsPosAppJourneyDetails.customerId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employeeCode, customerId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationApiModelsCommandsPosAppJourneyDetails {\n");
    
    sb.append("    employeeCode: ").append(toIndentedString(employeeCode)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
