/*
 * Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plugint.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IntegrationApiModelsCommandsRefund
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-24T06:53:25.443Z[GMT]")
public class IntegrationApiModelsCommandsCapturePayment {
  @SerializedName("retailerOrderNo")
  private String retailerOrderNo = null;

public IntegrationApiModelsCommandsCapturePayment retailerOrderNo(String retailerOrderNo) {
    this.retailerOrderNo = retailerOrderNo;
    return this;
  }

   /**
   * A retailer reference (e.g. order/invoice) number for this order that can be used for reconciliation purposes in the financial statements
   * @return retailerOrderNo
  **/
  @Schema(description = "A retailer reference (e.g. order/invoice) number for this order that can be used for reconciliation purposes in the financial statements")
  public String getRetailerOrderNo() {
		return retailerOrderNo;
	}

	public void setRetailerOrderNo(String retailerOrderNo) {
		this.retailerOrderNo = retailerOrderNo;
	}



  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationApiModelsCommandsCapturePayment integrationApiModelsCommandsCapturePayment = (IntegrationApiModelsCommandsCapturePayment) o;
    return Objects.equals(this.retailerOrderNo, integrationApiModelsCommandsCapturePayment.retailerOrderNo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(retailerOrderNo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationApiModelsCommandsCapturePayment {\n");
    sb.append("    retailerOrderNo: ").append(toIndentedString(retailerOrderNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
