/*
 * Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plugint.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.plugint.client.model.IntegrationApiModelsFormField;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * If the Type is FormPost, this will be populated with details to create the post
 */
@Schema(description = "If the Type is FormPost, this will be populated with details to create the post")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-24T06:53:25.443Z[GMT]")
public class IntegrationApiModelsFormPostAction {
  @SerializedName("formPostUrl")
  private String formPostUrl = null;

  @SerializedName("formFields")
  private List<IntegrationApiModelsFormField> formFields = null;

  public IntegrationApiModelsFormPostAction formPostUrl(String formPostUrl) {
    this.formPostUrl = formPostUrl;
    return this;
  }

   /**
   * The URL to which to submit the form post
   * @return formPostUrl
  **/
  @Schema(description = "The URL to which to submit the form post")
  public String getFormPostUrl() {
    return formPostUrl;
  }

  public void setFormPostUrl(String formPostUrl) {
    this.formPostUrl = formPostUrl;
  }

  public IntegrationApiModelsFormPostAction formFields(List<IntegrationApiModelsFormField> formFields) {
    this.formFields = formFields;
    return this;
  }

  public IntegrationApiModelsFormPostAction addFormFieldsItem(IntegrationApiModelsFormField formFieldsItem) {
    if (this.formFields == null) {
      this.formFields = new ArrayList<IntegrationApiModelsFormField>();
    }
    this.formFields.add(formFieldsItem);
    return this;
  }

   /**
   * An array of field names and values to post in the form.  The form post can be built programatically by enumerating the array.
   * @return formFields
  **/
  @Schema(description = "An array of field names and values to post in the form.  The form post can be built programatically by enumerating the array.")
  public List<IntegrationApiModelsFormField> getFormFields() {
    return formFields;
  }

  public void setFormFields(List<IntegrationApiModelsFormField> formFields) {
    this.formFields = formFields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationApiModelsFormPostAction integrationApiModelsFormPostAction = (IntegrationApiModelsFormPostAction) o;
    return Objects.equals(this.formPostUrl, integrationApiModelsFormPostAction.formPostUrl) &&
        Objects.equals(this.formFields, integrationApiModelsFormPostAction.formFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(formPostUrl, formFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationApiModelsFormPostAction {\n");
    
    sb.append("    formPostUrl: ").append(toIndentedString(formPostUrl)).append("\n");
    sb.append("    formFields: ").append(toIndentedString(formFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
