/*
 * Integration API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plugint.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IntegrationApiModelsLimits
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-24T06:53:25.443Z[GMT]")
public class IntegrationApiModelsLimits {
  @SerializedName("minPrice")
  private Integer minPrice = null;

  @SerializedName("maxPrice")
  private Integer maxPrice = null;

  public IntegrationApiModelsLimits minPrice(Integer minPrice) {
    this.minPrice = minPrice;
    return this;
  }

   /**
   * The minimum allowed for an order  An integer number in the lowest denomination in the currency being used (e.g. 1034 indicates $10.34)
   * @return minPrice
  **/
  @Schema(description = "The minimum allowed for an order  An integer number in the lowest denomination in the currency being used (e.g. 1034 indicates $10.34)")
  public Integer getMinPrice() {
    return minPrice;
  }

  public void setMinPrice(Integer minPrice) {
    this.minPrice = minPrice;
  }

  public IntegrationApiModelsLimits maxPrice(Integer maxPrice) {
    this.maxPrice = maxPrice;
    return this;
  }

   /**
   * The maximum allowed for an order  An integer number in the lowest denomination in the currency being used (e.g. 1034 indicates $10.34)
   * @return maxPrice
  **/
  @Schema(description = "The maximum allowed for an order  An integer number in the lowest denomination in the currency being used (e.g. 1034 indicates $10.34)")
  public Integer getMaxPrice() {
    return maxPrice;
  }

  public void setMaxPrice(Integer maxPrice) {
    this.maxPrice = maxPrice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationApiModelsLimits integrationApiModelsLimits = (IntegrationApiModelsLimits) o;
    return Objects.equals(this.minPrice, integrationApiModelsLimits.minPrice) &&
        Objects.equals(this.maxPrice, integrationApiModelsLimits.maxPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minPrice, maxPrice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationApiModelsLimits {\n");
    
    sb.append("    minPrice: ").append(toIndentedString(minPrice)).append("\n");
    sb.append("    maxPrice: ").append(toIndentedString(maxPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
